server:
  port: 8081

spring:
  config:
    import: "optional:configserver:"
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: training

rizzi:
  client:
    address:
      url: http://localhost:8082/addresses


